### ISSUE TITLE
Text installer limiting domainname to 15c

### ISSUE THREAD

**Issue by th122** [OpenIndiana/oi-docs#161]
(This may be the wrong place to put this, but with slim_source having no blurb to point at a better place and no issues there, I'm arguing that the problem can at least go into documentation if it remains unfixed :)

The text installer has a input limit to the domainname, stopping at char 15. Since not everyone is privileged to a 3-letter domainname, this is quite a showstopper, even though there are a number of possible workarounds, most of them adding a lot of extra steps to the task.

One possible "solution" would be to predefine the host in DHCP (and jump through the subsequent hooks of getting rid of the dhcp config afterwards, if undesired)

**Comment by Toasterson** [comment]
Hey, sorry for the late reply but we don't watch issues here on github that frequent.

The Installer has indeed a 15 Character limit but thats a problem with the Installer not the Os itself. Infact it is very easy to change afterwards in the configuration file /etc/nodename which most people simply do, if they even give the machine a name. I am against mentioning this limitation here, as it is either a Bug that should be reported on the illumos bugtracker or as PR in slim_source.
