### ISSUE TITLE
Approach for Adding Pull Request & PDF Build support to GitHub Actions

### ISSUE THREAD

**Issue by JMadgwick** [OpenIndiana/oi-docs#195]
At the moment GitHub Actions (added in #191) is only triggered by a push to master and it always builds and deploys. We don't get any build status indicators on PRs.

We should add a new workflow which is triggered by Pull Requests and runs just the linting and mkdocs build (not deploy). We could do this by creating a new branch from the [OI mkdocs-deploy-gh-pages](https://github.com/OpenIndiana/mkdocs-deploy-gh-pages/tree/oi) action. This would be identical but with deployment commands removed. A new workflow would then be configured to use that branch and run on pull requests only.

> Compared to Travis which was used previously, GH Actions [doesn't automatically build PRs from first time contributors](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), so a maintainer will need to approve these manually.

In addition to this, we could build the PDF versions of doc pages (using makepdf.sh) and add these to the website. This is straightforward to configure using the (_upload/download_)-artifact actions. There's no appropriate existing action for the PDF build. We could create one, this would require a whole new repo specially for that action. The main benefit of actions is reuse and we will need to reuse the code for building PDFs - in both a potential PR build workflow and the deploy workflow.

I would therefore suggest:
1. A new branch is added to [OI mkdocs-deploy-gh-pages](https://github.com/OpenIndiana/mkdocs-deploy-gh-pages/tree/oi) for PR builds, it could be called `oi-pr`.
2.    A.  A new repo under the OI project is created for holding a GH Action for building the PDFs, **or**
       B.  PDF build is configured and run directly from the workflow yaml - avoiding the need for an action but introducing some duplication.
3. A new workflow is created for PR builds (including PDF build) and PDF build is added to the current deploy workflow.

Of the options 2A and 2B, I think 2B is probably better - when balancing the extra work of creating and maintaining a separate repo for the action, against using the workflow yaml directly.

**Comment by Toasterson** [comment]
We could also make the Publish be gated behind an Evironment variable, by default disabled and in the Build on master we set that Variable as Option and publish. Same for generate PDF's We can use the Action flow repo as one script with switches that we turn on or off depending on the Workflow that imports that action.

**Comment by JMadgwick** [comment]
I don't think it's possible to use an action flow for building the PDFs.
The mkdocs repo uses alpine which makes sense for their use case (operate independently of workflow environment). However alpine does not work with texlive as it doesn't have that package available. I've investigated using a Debian image instead but this doesn't work well either - the docker images have far too few default packages. Installing the required dependencies for `texlive-xetex` would add 1GB to the docker image. Given that we are able to use a full installation of Ubuntu/Debian in the workflow directly, I see no reason to have an action flow which builds a very large container which is effectively identical. If this wasn't a problem then we would want to keep it part of the action flow repo.

Using an environment variable to control publishing works well, this avoids needing to create another branch for the action flow. [I got this working easily](https://github.com/JMadgwick/mkdocs-deploy-gh-pages/commit/45000a41094535ecf496920f90bc49eb30291b8d).

Adding an extra job with a conditional check for PR/non-PR to the workflow is enough to get build only PRs working. We also have the option of using two separate workflows which cater for PR and push separately ([e.g. this](https://github.com/JMadgwick/oi-docs/commit/e6c24adc56bb08a55bb6d5ea13ebc5a3a234fb92)). I think one workflow is probably better (although not as tidy) as this reduces duplication and eases maintenance.

[In this commit I've made the required changes for one workflow which incorporates a build only PR job and also includes PDF building.](https://github.com/JMadgwick/oi-docs/commit/31cc9ca5ad16d26ac9a05d360aa6c2f7779f8d84) I've checked the behaviour and it all works, just needs some rewording. If that looks good then I'll raise the required PRs on both repos. One problem with having two interlinked repos like this is the build will be broken for the period of time between one PR being merged and both being merged.

**Comment by JMadgwick** [comment]
If there's no further comments here, then I'll go ahead and submit a PR for the changes I've suggested in the final paragraph above.

**Comment by Toasterson** [comment]
Oh, sorry
LGTM!

**Comment by JMadgwick** [comment]
All changes now merged. [PDFs are now available directly from the website.](https://docs.openindiana.org/pdf/contrib/getting-started.pdf) :smiley: Future work will be to link these from pages with a suitably automated and efficient method.
