### ISSUE TITLE
OSDisc.com has closed, remove mentions from the documentation

### ISSUE THREAD

**Issue by domag02** [OpenIndiana/oi-docs#213]
As it can be seen in [this](https://www.linux.org/threads/osdisc-closed.24864/) forum post, OSDisc.com has closed.
Therefore, all mentions can be removed from the documentation.
Affected files:
- [docs/misc/openindiana.md](https://github.com/OpenIndiana/oi-docs/blob/fafb24f155e79d059d1d1dcb6ef1b10f6210622b/docs/misc/openindiana.md#L174)
- [docs/handbook/getting-started.md](https://github.com/OpenIndiana/oi-docs/blob/a126a08083e8e1256d2f554d130f1ad9851cac00/docs/handbook/getting-started.md#L305)

**Comment by JMadgwick** [comment]
Thanks for this, now fixed.
