### ISSUE TITLE
Add a separate page to the contrib section titled - Working with GIT

### ISSUE THREAD

**Issue by makruger** [OpenIndiana/oi-docs#52]
Provide basic instructions for working with git, for example commonly used commands, etc.

**Comment by AdrianKoshka** [comment]
I might try to tackle this, seems simple enough.

**Comment by alarcher** [comment]
You can copy/paste stuff from:
* http://hub.openindiana.ninja/?q=content/git-workflow
* https://github.com/OpenIndiana/oi-docs/blob/master/docs/dev/userland.md

**Comment by pyhalov** [comment]
Perhaps, just add some basic things, specific to oi-docs and references to git man pages or documentation?

**Comment by AdrianKoshka** [comment]
@alarcher @pyhalov thanks for the advice, I'll try working on something this thursday, today ended up being a bit more busy then I anticipated.

**Comment by AdrianKoshka** [comment]
Things got quite a bit busier then I thought but I managed to cobble a partial start.

- 5b1751ccb6bde2684124c574c832304084851d97
- 2c66f284a3932472c074665e57cf766089bde78f
- 4710fe1be07f1954ba9c6545fdb33b01632eed3f

https://github.com/AdrianKoshka/oi-docs/blob/work-with-git/docs/contrib/work-with-git.md

**Comment by makruger** [comment]
Hi Theo, thanks for spending time on this.

Please have a look at :https://openindiana.github.io/oi-docs/contrib/getting-started/
There you'll see what's already been written. 

Given we've already got the checkout process covered, I'd like you to focus your efforts on the day to day usage of Git with the assumption the repo has already been forked and cloned and the contributor already has a working copy. 

Start with the basics such as adding new or changed items with git add, committing them with git commit, using git diff, doing a push, doing a pull from the upstream master, etc. From there the instruction can move onto more advanced subjects such as branching, merging, etc.

Here is a useful reference which might provide some inspiration: http://rypress.com/tutorials/git/index

If you think however, we should provide a beginning to end tutorial, I am not opposed to that either.

**Comment by makruger** [comment]
Issue satisfied by https://github.com/OpenIndiana/oi-docs/pull/67
