### ISSUE TITLE
Update site parameters per changes in mkdocs 0.16

### ISSUE THREAD

**Issue by makruger** [OpenIndiana/oi-docs#58]
http://www.mkdocs.org/about/release-notes/#version-016-2016-11-04

**Comment by AdrianKoshka** [comment]
```
ERROR   -  Config value: 'theme'. Error: The theme 'spacelab' is no longer included in MkDocs by default and must be installed with pip. See http://www.mkdocs.org/about/release-notes/#add-support-for-installable-themesfor more details 

Aborted with 1 Configuration Errors!
```
I'll look into this.

**Comment by AdrianKoshka** [comment]
If I'm reading the error output of `mkdocs build` correctly...these warnings are to do with the theme used, not anything in `mkdocs.yml`

**Comment by AdrianKoshka** [comment]
I suppose we'd have to ask over at https://github.com/mkdocs/mkdocs-bootswatch

**Comment by alarcher** [comment]
Do you need an update of mkdocs in oi-userland as well?

**Comment by makruger** [comment]
I upgraded my locally installed copy on Linux Mint to 16.3 and the theme looks to still be working, and still reports those errors. Yes, I think the version being distributed by OI is probably 15.3 and would benefit from being upgraded. Whether anyone is actually using it....well, that's another matter.

WARNING -  Your theme does not appear to contain a 'main.html' template. The 'base.html' template was used instead, which is deprecated. Update your theme so that the primary entry point is 'main.html'.                                                                                                                                                                                  
WARNING -  Template variable warning: 'google_analytics' is being deprecated and will not be available in a future version. Use 'config.google_analytics' instead.                            
WARNING -  Template variable warning: 'copyright' is being deprecated and will not be available in a future version. Use 'config.copyright' instead.                                          
WARNING -  Template variable warning: 'favicon' is being deprecated and will not be available in a future version. Use '{{ base_url }}/img/favicon.ico' instead.                              
WARNING -  Template variable warning: 'site_name' is being deprecated and will not be available in a future version. Use 'config.site_name' instead.                                          
WARNING -  Template variable warning: 'page_description' is being deprecated and will not be available in a future version. Use 'config.site_description' instead.                            
WARNING -  Template variable warning: 'canonical_url' is being deprecated and will not be available in a future version. Use 'page.canonical_url' instead. 
WARNING -  Template variable warning: 'page_title' is being deprecated and will not be available in a future version. Use 'page.title' instead. 
WARNING -  Template variable warning: 'site_author' is being deprecated and will not be available in a future version. Use 'config.site_author' instead. 
WARNING -  Template variable warning: 'next_page' is being deprecated and will not be available in a future version. Use 'page.next_page' instead. 
WARNING -  Template variable warning: 'repo_url' is being deprecated and will not be available in a future version. Use 'config.repo_url' instead. 
WARNING -  Template variable warning: 'previous_page' is being deprecated and will not be available in a future version. Use 'page.previous_page' instead. 
WARNING -  Template variable warning: 'repo_name' is being deprecated and will not be available in a future version. Use 'config.repo_name' instead. 
WARNING -  Template variable warning: 'homepage_url' is being deprecated and will not be available in a future version. Use 'nav.homepage.url' instead. 
WARNING -  Template variable warning: 'toc' is being deprecated and will not be available in a future version. Use 'page.toc' instead. 
WARNING -  Template variable warning: 'content' is being deprecated and will not be available in a future version. Use 'page.content' instead. 
WARNING -  Template variable warning: 'meta' is being deprecated and will not be available in a future version. Use 'page.meta' instead.

**Comment by AdrianKoshka** [comment]
I mean, if someone really needs a more up to date version of mkdocs on OI I suppose they could use `pip` to install it.
