### ISSUE TITLE
Remove sudo from examples

### ISSUE THREAD

**Issue by frusen** [OpenIndiana/oi-docs#70]
Browsing the documentation I noticed the use of 'sudo' in the examples. I think a better convention would be to use '#' to indicate a command that must be invoked with more privileges than a regular user. '$', '%', or similar would be used to indicate a command run as a regular user.

Examples:

`# dd bs=4M if=./image.usb of=/dev/sdX status=progress && sync`

`$ vmstat`

The FreeBSD Handbook mentions it in its preface.

**Comment by makruger** [comment]
Yes, there is quite a bit of inconsistency in the way commands are described. Some use sudo and some nothing at all. This is something I'll need to review. Thanks for bringing it to my attention.

**Comment by xen0l** [comment]
@frusen would you be interested in fixing this? It's rather a simple thing to do and a good way how to start contributing.

**Comment by frusen** [comment]
@xen0l sure. I'll add some explanation about the convention somewhere in the introduction as well.

**Comment by frusen** [comment]
I've posted #71 see comment for details.
