### ISSUE TITLE
Document zpool installation

### ISSUE THREAD

**Issue by pyhalov** [OpenIndiana/oi-docs#86]
Need to explain how to install OpenIndiana to existing pool using text installer and what caveats exist.

**Comment by pyhalov** [comment]
I can write text, but it would be good to make some screenshots.

**Comment by makruger** [comment]
Hi Alexander, I can create some screenshots, but I don't have a very good understanding of this new capability. If you have a quick Gist you could point me to, that might help me visualize it.

**Comment by pyhalov** [comment]
Well. I can provide some text...
Since 2017.10 snapshot OpenIndiana text installer allows user to perform installation to existing pool. 
The feature can be used to install OI to the pool which has another operating system installed or to create root pool with custom configuration (for example, turn on compression).
This feature is considered advantageous, so user should have good understanding of what he is doing. To start installation to existing pool, you should use text installer and press F5 key when welcome screen appears. Note, that it is recommended to use minimal or text installation images for such type of installations. During installation to existing pool, you'll be presented with list of available pools, which satisfy space requirements. (Note, that pools are not checked for compatibility - i.e. you can select multi-dev pool, but this will lead to installation failure on later steps in best case or to unbootable system int the worst). As there's possibly already another OS instance installed to selected pool during installation process no additional users or filesystems are created (like RPOOL_NAME/export/home/USER_NAME). Swap and dump ZFS volumes also are not created and should be added later manually. Only root user will be available in created boot environment. As in some situations we would like only to transfer contents to new boot environment and avoid touching boot configuration at all, there's "Overwrite pool's boot configuration" option (on by default). Switching it off can be useful when you are intended to perform later boot configuration manually (for example, when you perform installation to pool which has other operating system or boot loaders installed).

**Comment by makruger** [comment]
OK, I will try to write up a section for this during the upcoming holidays.
