### ISSUE TITLE
No docs on how to simply connect through PPPoE to my isp

### ISSUE THREAD

**Issue by brancoliticus** [OpenIndiana/oi-docs#95]
Ubuntu has the very nice and simple pppoeconf app exactly for the purpose of dealing with pppoe. In the OpenIndiana docs I only found references to pppd. That is as far as I could understand from reading 'man pppd' a way to build scripts on top of raw network protocols. I am willing to put on the effort to help create some sort of simple to use script to solve the issue of connecting to my ISP. If anyone could guide me through such an effort I would appreciate it.

**Comment by Toasterson** [comment]
Hi, sorry we usually don't look at issues here. 

As far as I know we do not support PPPoE configurations without a router inbetween the Computer and the Internet. Which is common today almost everywhere. I am not aware that we have PPPoE support at all in the networking tools. Most of our stack has been focused on Ethernet.
